%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Nick\Documents\Fatigue Experiments\NI DAQ\emg_data.txt
%
% Auto-generated by MATLAB on 01-Sep-2020 11:51:02

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [1, 3];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "Var5", "Var6", "Var7", "Var8"];
opts.SelectedVariableNames = ["VarName1", "VarName2", "VarName3", "VarName4"];
opts.VariableTypes = ["double", "double", "double", "double", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var5", "Var6", "Var7", "Var8"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var5", "Var6", "Var7", "Var8"], "EmptyFieldRule", "auto");

% Import the data


%% Convert to output type
emg_times = table2array(readtable("C:\Users\Nick\Documents\Fatigue Experiments\NI DAQ\emg_data.txt", opts));

%% Clear temporary variables
clear opts

%%import emg data for 8 channels
emg_data = open("emg_data.mat").data;

%%get period (s) from frequency (Hz)
period = 1/emg_times(3,1)

%%create time column 
emg_data = [[period:period:size(emg_data,2)/1000];emg_data];
